// This file is machine-generated - edit with caution!
/**
 * @fileOverview This file defines the global `ai` object, which is the
 * entrypoint for all Genkit capabilities. It is used to define prompts, flows,
 * and models.
 *
 * It is also used to configure the Genkit environment, such as the plugins that
 * are used to connect to different models and services.
 *
 * This file is automatically generated by the Firebase extension for Genkit, and
 * should not be modified directly.
 */
import {genkit} from 'genkit';
import {googleAI} from '@genkit-ai/googleai';
import {firebase} from '@genkit-ai/firebase';

const ai = genkit({
  plugins: [
    firebase(),
    googleAI({
      apiVersion: ['v1beta'],
    }),
  ],
  flowStateStore: 'firebase',
  traceStore: 'firebase',
});

export {ai};
